insert into genres(id, parent_id, slug, name) values(1, null, 'legkoe-chtenie', 'Легкое чтение');
insert into genres(id, parent_id, slug, name) values(2, 1, 'fantastica', 'Фантастика');
insert into genres(id, parent_id, slug, name) values(3, 1, 'boeviki', 'Боевики');
insert into genres(id, parent_id, slug, name) values(4, 1, 'detektivy', 'Детективы');
insert into genres(id, parent_id, slug, name) values(5, 4, 'thriller', 'Триллер');
insert into genres(id, parent_id, slug, name) values(6, 4, 'krutoy-detectiv', 'Крутой детектив');
insert into genres(id, parent_id, slug, name) values(7, 4, 'ironic-detectiv', 'Иронический детектив');
insert into genres(id, parent_id, slug, name) values(8, 1, 'fantasy', 'Фэнтези');
insert into genres(id, parent_id, slug, name) values(9, 1, 'romany', 'Романы');
insert into genres(id, parent_id, slug, name) values(10, null, 'serious-chtenie', 'Серьезное чтение');
insert into genres(id, parent_id, slug, name) values(11, 10, 'biopic', 'Биографии');
insert into genres(id, parent_id, slug, name) values(12, null, 'delovaya-literatura', 'Деловая литература');
insert into genres(id, parent_id, slug, name) values(13, 12, 'career', 'Карьера');
insert into genres(id, parent_id, slug, name) values(14, 12, 'marketing', 'Маркетинг');
insert into genres(id, parent_id, slug, name) values(15, 2, 'good-fantastic', 'Хорошая фантастика');
insert into genres(id, parent_id, slug, name) values(16, 3, 'horror-boevic', 'Страшный боевик');
insert into genres(id, parent_id, slug, name) values(17, 4, 'classic', 'Классический детектив');
insert into genres(id, parent_id, slug, name) values(18, 8, 'light-fantasy', 'Легкое фэнтези');
insert into genres(id, parent_id, slug, name) values(19, 2, 'russian-fantastic', 'Русская фантастика');
insert into genres(id, parent_id, slug, name) values(20, 5, 'horror-thriller', 'Ужасный триллер');
insert into genres(id, parent_id, slug, name) values(21, 9, 'russian-roman', 'Русский роман');