insert into tags (id, description) values (1, 'современная литература');
insert into tags (id, description) values (2, 'классическая литература');
insert into tags (id, description) values (3, 'зарубежная литература');
insert into tags (id, description) values (4, 'фэнтези');
insert into tags (id, description) values (5, 'английская литература');
insert into tags (id, description) values (6, 'русская литература');
insert into tags (id, description) values (7, 'американская литература');
insert into tags (id, description) values (8, 'фантастика');
insert into tags (id, description) values (9, 'детская литература');
insert into tags (id, description) values (10, 'детектив');
insert into tags (id, description) values (11, 'любовь');
insert into tags (id, description) values (12, 'мистика');
insert into tags (id, description) values (13, 'юмор');
insert into tags (id, description) values (14, 'сказка');
insert into tags (id, description) values (15, 'англия');
insert into tags (id, description) values (16, 'художественная литература');
insert into tags (id, description) values (17, 'психология');
insert into tags (id, description) values (18, 'философия');
insert into tags (id, description) values (19, 'экранизировано');
insert into tags (id, description) values (20, 'любимое');
insert into tags (id, description) values (21, 'антиутопия');
insert into tags (id, description) values (22, 'books you must read before you die');
insert into tags (id, description) values (23, 'роман');
insert into tags (id, description) values (24, 'франция');
insert into tags (id, description) values (25, 'дайте две');
insert into tags (id, description) values (26, 'young adult');
insert into tags (id, description) values (27, 'война');
insert into tags (id, description) values (28, 'история');
insert into tags (id, description) values (29, 'детство');
insert into tags (id, description) values (30, 'жизнь');
insert into tags (id, description) values (31, 'драма');
insert into tags (id, description) values (32, 'россия');
insert into tags (id, description) values (33, 'книжное путешествие');
insert into tags (id, description) values (34, 'советская литература');
insert into tags (id, description) values (35, 'триллер');
insert into tags (id, description) values (36, 'америка');
insert into tags (id, description) values (37, 'немецкая литература');
insert into tags (id, description) values (38, 'вампиры');
insert into tags (id, description) values (39, 'школьная программа');
insert into tags (id, description) values (40, 'рассказы');
insert into tags (id, description) values (41, 'магия');
insert into tags (id, description) values (42, 'дети');
insert into tags (id, description) values (43, 'русская классика');
insert into tags (id, description) values (44, 'биография');
insert into tags (id, description) values (45, 'english');
